### ISSUE TITLE
Will the site be up for the 2021 season?

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#1]
Hi, since Fantesh stopped we have been using a web scraper and a complicated google sheets solution.  Are you going to be using this for the 2021 season? Is it at a stage that it could be used?

Thanks, David

**Comment by mdryden** [comment]
Hi David, sorry for the late response.

Yes, I will be running the site this year.  I'm still putting the finishing touches on it, but hope to have it ready soon.

**Comment by davidkinetisense** [comment]
Thanks for getting back to us.  This is so great as we have been
running with a spreadsheet since the Fantesh shutdown.  This is so
great.  Regards,  David

On Tue, Jun 29, 2021 at 6:13 AM Michael Dryden ***@***.***> wrote:
>
> Hi David, sorry for the late response.
>
> Yes, I will be running the site this year. I'm still putting the finishing touches on it, but hope to have it ready soon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
David Schnare
Kinetisense Inc.
403-526-3556

www.kinetisense.com
