### ISSUE TITLE
Schedule looks suspicious

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#10]
Just generated my schedule and it doesn't look right.  Basically instead of having 4 rows showing the 4 matchups it just has all 8 teams listed down the left side.  Hopefully this is just a display problem.

**Comment by mdryden** [comment]
League link?

**Comment by mdryden** [comment]
Also, this kind of thing is why I'm slow in pushing the "ready" button...I want to make sure potential bugs like this don't derail everyone's season 😃

**Comment by kamikazecanuck** [comment]
4XVWS3uyiwxXU4BAg0S7

**Comment by kamikazecanuck** [comment]
Ya fair enough. 

Do you remember my spiel 2 years ago about giving the week at least 24 hours to settle after the last game because even the CFL is doing stat reconciliation? I hope you’re considering that. Caused much consternation amongst Poolies last time.

**Comment by mdryden** [comment]
I don't see a schedule at all for this league yet.  What you're seeing on the league home page is the standings, which is why it's just a list.  If you go into commissioner options > schedule you can select your playoff type, duration, and then generate the schedule.  Maybe I need to make this step more clear; though it won't let you start the draft without doing it.

You still can't start the draft yet in live, but you can generate and review the schedule.

**Comment by kamikazecanuck** [comment]
No, the standings are below. I am familiar with the layout. The schedule for week 1 is there in it’s own box. It can be clicked to go to the next week and all the other weeks of the schedule. However all teams are just lined up on the left margin. It does seem to be following the schedule that’s been generated which I can see in commissioner tools.

**Comment by mdryden** [comment]
I did change the layout of the schedule section of the homepage recently, maybe that's what you're describing.  The layout where the teams were on the far left and right, with the scores in the middle did not work well on mobile, so I changed to more of a "TV style" layout, with the away team above the home team.

I'm thinking it's ok, but I will continue to test.

**Comment by kamikazecanuck** [comment]
Ah ok. It is just an aesthetic thing then. I prefer the old layout but to each his own. Perhaps a line between each matchup? Kind of looks like a big list of the teams in your league. Like the standings.

**Comment by mdryden** [comment]
Yea to be honest I liked the other layout better too, but I had a hard time making it work on a phone and I'm trying to avoid too many "if mobile do this, if desktop do this" type screens.

It's just visual though, and I may refine it as things go on.

**Comment by mdryden** [comment]
I'm still not super happy with the look here, but I noticed while working on your league preview issue that it looks extra bad with that many teams.  I added a small border between the matchups which may help a bit.  Going to leave this one open for a while yet though.

**Comment by mdryden** [comment]
Decided to stay up a bit later tonight and test out some changes to matchups I dreamed up over the weekend.  I think it's a big improvement, let me know what you think.

Changes are on the home page, the league page, and matchups

**Comment by kamikazecanuck** [comment]
Way better! Only thing is the error where instead of showing my matchup on the homepage it shows another random matchup is back.

**Comment by mdryden** [comment]
What the heck, how did that come back?  I'll fix that this evening.

**Comment by mdryden** [comment]
Fixed now.

**Comment by kamikazecanuck** [comment]
Yes, thanks.
