### ISSUE TITLE
Player Filters

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#12]
The "Def" filter brings up nothing.  I think it's meant to sort all defensive players?

The "FA" filter also doesn't bring up anything.  Is that meant to show all unsigned players?  May be something that works after draft?

**Comment by mdryden** [comment]
Didn't realize the def filter wasn't working, thanks.  I did notice the FA one but forgot to implement it last night.  Call these "coming soon" :).

**Comment by kamikazecanuck** [comment]
Somewhat related.  The sort feature on the the columns in the player tab don't seem to sort.  (The little arrows that sort by ascending and descending)

**Comment by mdryden** [comment]
These will be fixed in the next update, which will be in a few days.

Am I crazy though - where are you seeing the DEF filter?  Maybe I removed it and forgot?

**Comment by kamikazecanuck** [comment]
Ya it’s still there. It’s one of the buttons on the player screen…

**Comment by kamikazecanuck** [comment]
Just noticed on mobile the filter buttons don’t change colour when you press them.

**Comment by mdryden** [comment]
Re: mobile - possibly specific to a certain browser?  Working ok for my on Android / Chrome.

The DEF filter was a configuration error - it wasn't supposed to be available as a filter, but it was configured wrong in live.  It's gone now.  The free agent button should be working properly now as well.
