### ISSUE TITLE
Some active players are not available in the player list

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#13]
This is a bug in the data source I'm using to pull rosters from the CFL.  I am hoping the CFL can address the issue, otherwise I will apply a manual fix once I have time to thoroughly test.

The full list of affected players (as of July 25th) is:

Josh Banks (BC), Jake Bofshever (BC), Tim Bonner (BC), Jarell Broxton (BC), James Butler (BC), Reggie Corbin (BC), Jamal Custis (BC), Jalon Edwards-Cooper (BC), Stefan Flintoft (BC), Jake Ford (BC), Keyston Fuller (BC), Alfred Green (BC), Matt Guevremont (BC), Niklas Gustav (BC), Obum Gwacham (BC), Court Hammond (BC), KiAnte Hardin (BC), Cordell Hastings (BC), Keon Hatcher (BC), Jeff Hector (BC), Trevon Hill (BC), Ben Hladik (BC), Kayden Johnson (BC), Johnathon Johnson (BC), Austin Joyner (BC), Ufomba Kamalu (BC), Jermaine Kelly (BC), Cam Kitchen (BC), Dana Levine Jr. (BC), Boqiao Li (BC), Matt McConnell (BC), Marcus Norman (BC), Tyler Packer (BC), Shea Patterson (BC), Kent Perkins (BC), Tyvis Powell (BC), TJ Rahming (BC), Jimmie Robinson Jr. (BC), Nathan Rourke (BC), Nydair Rouse (BC), Kevin Thurmon (BC), Jesse Walker (BC), Alex Wesley (BC), Jordan X. Williams (BC), Jordan M. Williams (BC), Bejour Wilson (BC), Takeru Yamasaki (BC), Bryce Bell (CGY), Cody Grace (CGY), Elliot Graham (CGY), Ryan Grant (CGY), Luther Hakunavanhu (CGY), Charlie Moore (CGY), Malcolm Thompson (CGY), Ben Whiting (CGY), Quan Bray (MTL), Prince Charles Iworah (MTL), Nate Behar (OTT)

**Comment by mdryden** [comment]
I've sent an email to the CFL to see if they can help me understand the behavior of these ids.  I suspect that maybe these are brand new players who may not get an id set until they start accumulating stats.

In theory I can match them up using some of the other data, I just need to confirm (or hope) that the id will remain the same if I match them manually.

This issue will probably take some time to fix.  As most of the players are not (currently at least) what I'd consider high value fantasy targets, I don't consider this a critical issue but I will do my best to get a fix in place before the start of the season.  I have a strong suspicion that any of these players who show up on the stat sheet for week 1 will get fixed automatically, but that isn't ideal for anyone looking to draft one of them.

I'll continue to post updates to this issue thread, for anyone following.

**Comment by kamikazecanuck** [comment]
Mostly unknowns fortunately, except for 2 I would say.

**Comment by mdryden** [comment]
My theory is that these are all players who have never played a game, but I haven't checked them all to be sure.

I have a few ideas on how to get them included but I'd like to give my contact at the CFL a bit of time to respond before I take any action.

**Comment by kamikazecanuck** [comment]
Ya, I would rather proceed like this than risk stability implosion.

**Comment by cstevens780** [comment]
There is one player on this list who has played one previous season who is likely slated for a 1000 yard season. I am putting a comment in so I know when the bug is fixed so I can add him as a free agent as I couldn’t draft him

**Comment by kamikazecanuck** [comment]
Please tell me who. I promise not to tell your fellow Poolies

**Comment by kamikazecanuck** [comment]
I assume it's Bray...

**Comment by cstevens780** [comment]
Yup it’s bray he had 800 some yards last year in 15 games, he was just warming up
________________________________

**Comment by kamikazecanuck** [comment]
Ya he’s really smoking..

**Comment by mdryden** [comment]
This is fixed now.
