### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by cstevens780** [110yards/fantasy#144]
I am modifying the league based on what worked and what didn’t last year. To fix the biggest problem we are looking to add two bye spots to ensure that if you have a QB and a RB on the same team you do not have to drop both. When I go to change the roster limits I am given error 422

**Comment by bohsask** [comment]
I tried adjusting the roster settings and encountered the same thing.

**Comment by mdryden** [comment]
Sorry about this guys, it looks like an issue with the new option to allow more qb/rb/k positions for existing leagues.  Existing leagues don't have that value set and the site blows up trying to update your options.

Fix coming shortly.
