### ISSUE TITLE
League matchup preview is wrong for some users in leagues

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#15]
When the draft is started, the schedule matchups are locked in and are added to each user's home page.

This matchup should be the matchup for that roster in that league, but for leagues with more than 2 teams, all users are seeing the same matchup (which may not be their personal matchup).

**Repro steps:**

Create a new league with 4+ teams.

Start the draft.  Review the home page for all users; each user should see a preview of their current week matchup, but some users will see the wrong matchup.

**Fix:** 

1) Create a migration endpoint to manually correct anyone with a broken matchup.

2) Fix the start draft command so it adds the correct matchup for each user.

**Comment by mdryden** [comment]
https://github.com/mdryden/110yards-api/issues/58

**Comment by mdryden** [comment]
This is fixed now.

**Comment by kamikazecanuck** [comment]
Cool
