### ISSUE TITLE
Manage Teams not up?

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#16]
The Manage Teams function in commissioner tools doesn't do anything.  I think this is pretty essential for league management.  Sometimes commissioner needs to cut a player a GM has hoarded illegally.

**Comment by mdryden** [comment]
Sorry, but right now there are no extra controls for commissioners, other than configuring the league.

I have a few todos recorded for this, but they aren't as critical as other features for go-live.  Call this one coming soon.

Also, manage teams is just for the league - pre-draft, you can use it to kick a team from the league.  Any commissioner functions for managing other teams will be integrated into the roster pages.

**Comment by kamikazecanuck** [comment]
Ah, I see.  Thought it was migrating to it's own page.  Thanks.

**Comment by mdryden** [comment]
Commissioner controls request moved to https://github.com/mdryden/110yards/issues/42
