### ISSUE TITLE
Reset League

### ISSUE THREAD

**Issue by bohsask** [110yards/fantasy#163]
I messed up doing some testing and I started and stopped our draft, which is apparently irreversible.  Can you reset this for us?  League ID:xDTpKTT4DRK3MAf4PLSD

**Comment by mdryden** [comment]
Yes, once the draft is ended a bunch of stuff gets initialized once for the league.

I'll see what I can do about resetting it and get back to you.  I'll try to get to it today, but I may not have time.

**Comment by mdryden** [comment]
This should be done now.  I re-used the renew league function so it's just like you started again after 2021.  That said, I've never tried this before other than a few minutes of testing, so if you run into anything weird please let me know.

**Comment by bohsask** [comment]
Thanks for doing that, and yep it worked.
