### ISSUE TITLE
Request: Scoring Edits

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#17]
Request to be able to edit scoring parameters.  I know that's been in the works for a while but it seems especially weird this year.

A point per catch is pretty standard now. As is 2 point tackles.

**Comment by mdryden** [comment]
I've been thinking I should probably add a warning to the start draft button - you can edit the scoring settings, but only until the draft is started.

A big "The following things can no longer be edited" type message before allowing the commissioner to start the draft would probably be useful.

**Comment by kamikazecanuck** [comment]
In retrospect yes.  Oh well, it's a learning process.

Thanks so much for offering to edit scoring:

Attempts	0	
Completions	0	
Yards (net)	0.05	20 yards = 1 point
Touchdowns	4	
Interceptions	-2	
		
Rushing		
Yards (net)	0.1	10 yards = 1 point
Rushes	0	
Touchdowns	6	
		
Receiving		
Receptions	1	
Yards	0.1	10 yards = 1 point
Touchdowns	6	
		
Offense		
Fumbles	-2	
Two point converts	2	
		
Kicking		
Punt/kick-off singles	1	
Field goal made	3	
Field goal misses	-1	
Field goal singles	1	
One point converts	1	
		
Kick Returning		
Yards	0.05	20 yards = 1 point
Touchdowns	7	
		
Defense		
Tackles	2	
Special teams tackles	2	
Sacks	3	
Interceptions	5	
Fumbles forced	2	
Fumbles recovered	3	
Passes knocked down	1
	
4XVWS3uyiwxXU4BAg0S7

**Comment by kamikazecanuck** [comment]
I assume there's still that CFL oddity of not counting defensive touchdowns?

**Comment by mdryden** [comment]
Yep that's right.  Defensive touchdowns aren't included in the boxscore, which is what I use for scoring.

I have some thoughts on a workaround (the numbers are available on the player's stats), I just need to figure out a way to implement it that's both efficient and not confusing to users.

**Comment by mdryden** [comment]
I've made the changes for you - can you review and confirm they look right?

**Comment by kamikazecanuck** [comment]
Yes, looks good. Thank you so much for going above and beyond!

**Comment by mdryden** [comment]
👍

**Comment by kamikazecanuck** [comment]
Hi Pudds,

If it’s not too much trouble can I change the return yards to 1 point per 25 yards? If it too much trouble don’t worry about it. 

Thanks again.
