### ISSUE TITLE
Incorrect Canadians

### ISSUE THREAD

**Issue by HoldenCaulfield23** [110yards/fantasy#177]
Question I have is why am I seeing a maple leafs next to players like Cody Fajardo, Eugene Lewis, DaVaris Daniels, Markeith Ambles, etc. Certainly looks like most of the maple leafs are the Canadians, just a few that are off. At first I thought maybe the long term guys were flagged due to the "naturalized american" thing, but Adam Bighill doesn't have one so it's very odd to me.

We decided in our league to have a Flex that has to be a Canadian and that's just throwing us off a little bit. Minor quibble in the grand scheme, just curious if this is a known bug or something.

Thanks for site though, it's really going well overall!

**Comment by kamikazecanuck** [comment]
I raised the same issue. Apparently the API doesn’t distinguish between global and Canadian players.

**Comment by mdryden** [comment]
Yes, this is a limitation of the CFL's API, which hasn't been updated to differentiate between Canadian and global players.

For example, this is what the CFL returns for Fajardo:

```
{
    "data": [
        {
            "cfl_central_id": 160140,
            "stats_inc_id": 557390,
            "first_name": "Cody",
            "middle_name": "",
            "last_name": "FAJARDO",
            "birth_date": "1992-03-29",
            "birth_place": "Los Angeles, California",
            "height": "6.02",
            "weight": 215,
            "rookie_year": 2016,
            "foreign_player": false,
            "image_url": "http://d3ham790trbkqy.cloudfront.net/wp-content/uploads/players/c/cody-fajardo-160140.png",
            "school": {
                "school_id": 414,
                "name": "Nevada"
            },
            "position": {
                "position_id": 1,
                "offence_defence_or_special": "O",
                "abbreviation": "QB",
                "description": "Quarterback"
            },
            "team": {
                "is_set": true,
                "team_id": 7,
                "location": "Saskatchewan",
                "nickname": "Roughriders",
                "abbreviation": "SSK",
                "season": 2022,
                "uniform": 7
            }
        }
    ],
    "errors": [],
    "meta": {
        "copyright": "Copyright 2022 Canadian Football League."
    }
}
```

That ```"foreign_player": false,``` is what controls the maple leaf icon.  It should also reflect the way that the CFL treats these players for the purposes of the ratio as well (except for QBs which don't affect the ratio either way).

**Comment by mdryden** [comment]
More discussion can be found here: https://github.com/mdryden/110yards/discussions/156
