### ISSUE TITLE
Mobile chrome issue

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#181]
The scores don't work in mobile mode.

The display as 0.

Making it a desktop view makes it impossible to use.

I mentioned this last year.

Can you see if this can be addressed?

**Comment by davidkinetisense** [comment]
![Screenshot_20220610-161137.png](https://user-images.githubusercontent.com/64800266/173158364-2f33355a-19d0-4c5f-9cd9-6185e1fbd40a.png)

**Comment by mdryden** [comment]
Looks like a bug on the team page.  For now you can use the matchup page (click vs between the matchup on the league page).

I'll get this fixed as soon as possible.
