### ISSUE TITLE
Defensive touchdowns

### ISSUE THREAD

**Issue by gorillatrain** [110yards/fantasy#182]
Why are there no points allowed for defensive touchdowns?

**Comment by mdryden** [comment]
Defensive touchdowns aren't included in the player stats returned by the CFL's API, they are only included at the team level.

For example, here's Tre Watson from Thursday's game:

![image](https://user-images.githubusercontent.com/5611490/173371876-432d86a7-2786-4202-82dc-2325db451023.png)
