### ISSUE TITLE
Waiver $ charged after failed transaction

### ISSUE THREAD

**Issue by latecowboy** [110yards/fantasy#187]
I tried to add a second running back by accident.  It charged me my waiver fee, failed to add the running back (illegal roster move) and failed to drop the discard player from my bench.  Then my waiver rounds ended, I had other waivers lined up (for less $) that should have processed because I still had the discard player on my roster.  

----

**More information**

This occurs when someone attempts to add a player with a position limit (eg: a Running back) and doesn't drop a player that will make room (eg: drops a receiver).

For most waiver claims the site is able to figure out whether it will be successful or not, and fail early, leaving the budget alone, but in this edge case, the processing thinks it's going to succeed because this is the highest bid, it's doesn't put the player over the total roster size, and it's not over-budget.  Then when the add/drop service attempts to add the player, it bails out because it recognizes that adding a second running back will violate the league configuration.  It stops the add (good) but doesn't give the money back (bad).

I've added a fix which ensures that if a waiver claim fails late, the money isn't deducted, and I will run a script which cleans up all waiver budgets affected by this bug.

**Comment by latecowboy** [comment]
Update:  I found out from the other players that the RB was not able to be picked up with their waivers after my failed attempt.  Seems like a bug.

Awesome job on this website, by the way.  We are really having fun with it.

**Comment by mdryden** [comment]
Thanks for the report, I'll take a look.

I will note that if an add/drop waiver fails, it's expected that the drop won't proceed.  You shouldn't have gotten charged for the failed waiver claim though, if that happened it's an error I'll need to fix.  If you can give me your league ID (from the URL) and roster name I can investigate more and correct your balance.

**Comment by latecowboy** [comment]
The league is Barley Hoppers, JcsyfUjCjHgJH82gHM0S
My Team is the Mundare Marauders

Thanks!

**Comment by mdryden** [comment]
Confirmed, your waiver total is incorrect.

This is interesting, no one else seems to have been affected in your league, despite a lot of other failed claims.

I will work on a fix for this today and get your balance corrected by the end of the week.

**Comment by mdryden** [comment]
The script to correct waiver budgets has been run.  Looks like 7 rosters were affected, including yours.  @latecowboy you should see your corrected budget now.

**Comment by latecowboy** [comment]
Confirmed! My budget is correct now.  Thanks for the prompt fix!
