### ISSUE TITLE
Bede score

### ISSUE THREAD

**Issue by EElks** [110yards/fantasy#189]
BEDE scored several points but is scored as minus 188.  Plus update.  Thanks Michael.

**Comment by mdryden** [comment]
You should double check your league scoring settings, he is scored correctly in my league.

If you don't see an obvious mistake, please share your league Id and I can take a look.

**Comment by EElks** [comment]
Thanks Michael.  That was the problem.  It subtracted 100 points for every missed field goal.  Yikes.  Fixed now.

**Comment by mdryden** [comment]
Haha, now that's a penalty, I love it.
