### ISSUE TITLE
DB / LB positions not synced

### ISSUE THREAD

**Issue by DamonB88** [110yards/fantasy#198]
Players are listed as LB when looking under the Players tab, but when I add them to my roster their position is DB so I can't place them under LB positions. Such as Jeawon Taylor (EDM LB but his position is DB beside his name).
This issue is common with the SLB players. 

There have also been players that have been switched from LB to DB and back on a week to week basis (Both Titus Wall (CGY) and Donald Rutledge (WIN) are LB but the site switches their position back and forth).

This is on an Android phone but same issue occurs on my PC.

Not sure if there is a fix for it or if this is CFL database issues, but hoping there can be consistency with the listing so I don't bid for a LB only to get a DB i can't start.

Thanks!

Damon

**Comment by mdryden** [comment]
Sorry but this is all about how the CFL categorizes their players, the position information comes directly from the API. You should always use the site as a guide and make sure that the site considers the player to be an LB if you need an LB.

Alternatively, I might suggest that you use a defensive flex slot instead next year.  Our league switched to non-positional defensive spots and we find it much better.
