### ISSUE TITLE
Game Log not sorting chronologically

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#199]
I believe the intent when you click a player is that it shows all his previous game stats sorted chronologically with the most recent week being at the top.  Right now it's not doing that.  Seems pretty random.

**Comment by mdryden** [comment]
Yea I noticed this one a while ago too, it's been on my radar.  I actually just fixed it this morning and didn't realize you'd opened a bug for it as well.

**Comment by kamikazecanuck** [comment]
Cool, thanks.
