### ISSUE TITLE
League ID / Naming Issues

### ISSUE THREAD

**Issue by ShagginTurtles** [110yards/fantasy#2]
When you create a league, it asks for a league ID which names it. I created one with a funky name and no password but people couldn't join

So after someone made one called Test with the password Test, it still wouldn't work. Needed to use League ID: Ss5sQqm4r2UQ0LCxdeqF

I imagine the league IDs should be codes like that but then I wouldn't call the names League IDs too

**Comment by mdryden** [comment]
Are you confusing league id with league name?  (If you are, it's my fault not yours).

The league id is auto when you create the league, and it's also what used to join the league (the invite link uses the id).  The name is only for your own use; it shows up on the league home page.

**Comment by mdryden** [comment]
I should probably put an FAQ item in for this and how to invite.

**Comment by cstevens780** [comment]
It would be nice to show the league ID below the league name under the “commissioner tools - teams option” tab for the commissioner to give out if the invite link doesn’t work

**Comment by mdryden** [comment]
That's a good idea.  I'll add it there (or maybe on the registration tab) so it can be copied.
