### ISSUE TITLE
Kai Locksley Position

### ISSUE THREAD

**Issue by EElks** [110yards/fantasy#204]
I have used Kai Locksley as a WR but now he's listed as a QB. Could this be changed back to WR because he almost always plays that position. He takes QB sneaks as a QB but i need him as a WR.

**Comment by EElks** [comment]
Thanks

**Comment by mdryden** [comment]
For the record, I didn't do anything here.  Position assignments come directly from the CFL's data.

**Comment by EElks** [comment]
It worked out.

We've had a lot of fun this year. Thanks Michael.
