### ISSUE TITLE
playoffs week 17 start

### ISSUE THREAD

**Issue by redblacks** [110yards/fantasy#205]
Hey just wondering if yoyur able to switch our start of playoffs date to week 17 as the 1st week   we just noticed that week 16 is a triple bye week so hard to start playoffs that week 
hoping to do week 17 and 18 as playoffs let me know if this is possible to do thanks Nick
League  Redblacksboys  

**Description**
A description of the question or request

**League ID**
Please include your league id if applicable.

**Roster / Name**
Please include the affected roster name if applicable.

**Additional information**
Screenshots or anything else you think might be useful to help understand the request.

**Comment by mdryden** [comment]
Sorry, but it's not possible to change the schedule after it's started 😞
