### ISSUE TITLE
Forgot to add a loser playoff

### ISSUE THREAD

**Issue by KAI1984** [110yards/fantasy#206]
**Description**
I forgot to add a loser game to my league playoffs.  

**League ID**
miUCx9qUfl3goKKEEDxL

**Comment by mdryden** [comment]
I might be able to do this.  I'll take a look.

**Comment by KAI1984** [comment]
Hey, not sire if you were able to get a loser game sorted or not, but if possible could we add one to the week we have our championship game (the week after next)?

Kai Horsfield
403.891.5241
________________________________
