### ISSUE TITLE
Third Place Game

### ISSUE THREAD

**Issue by EElks** [110yards/fantasy#209]
Hi Michael. We are having our championship game next week and I notice that there's no third place game. Is it possible to add this--populating it with the two losers of the playoff games from this week. The teams from the Loser Game of this week don't need to play again.

**Comment by mdryden** [comment]
Sorry, but the playoff system doesn't support a 3rd place game.

**Comment by EElks** [comment]
No problem. We found a way forward. Thanks for the great season!
