### ISSUE TITLE
Playoff Tie Breaker 

### ISSUE THREAD

**Issue by SteveTaskersSon** [110yards/fantasy#211]
Hi,
Not an issue, just a question.

What is the tie breaker formula for playoff games?  The FAQ has the formula for regular season standings, but not playoffs.  Would it carryover to playoffs? 

Thanks!

**Comment by mdryden** [comment]
Good call - I will add it.

The tie breaker for the playoffs is simply the seeding.  Decimal scoring means that ties should be pretty uncommon in a single game, but in the event if a tie, the top seed for the matchup moves on (eg: 1 beats 2, 2 beats 3, etc)
