### ISSUE TITLE
Playoff matchups not populated "TBD"

### ISSUE THREAD

**Issue by Beavers22** [110yards/fantasy#213]
**Describe the bug**
Our playoff are supposed to start week 17 (this week). The matchups didn't populate. It says "TBD" for all matchups.
![Screenshot_20220927-102023](https://user-images.githubusercontent.com/114508486/192582696-9234f34a-396e-455d-9a6b-a7ad174f9d7d.png)

**League ID**
Barley Hopper - JcsyfUjCjHgJH82gHM0S

**Roster name**
Birchgrove Beavers

**Screenshots**

**Device information**
Please indicate if you are using a mobile device or desktop, and the browser you are using, if applicable.

**Comment by mdryden** [comment]
I'm not sure what happened here - I've re-triggered the end of week calculations and they appear to have calculated correctly.  I'll be keeping an eye on this one, thanks for letting me know.

**Comment by argos1873** [comment]
My league has the same issue, I think it might be a broader sitewide issue

**Comment by Beavers22** [comment]
Thanks for the matchup fixes. We noticed we can't add players now, all day today. we get an error saying waivers are still being processed. Maybe it's related? Anything you could do to fix would be greatly appreciated, thanks. 

![Screenshot_20220928-174649](https://user-images.githubusercontent.com/114508486/192911342-1c80cac6-7fd6-4c32-ae22-0dc8f29746c9.png)

**Comment by mdryden** [comment]
> My league has the same issue, I think it might be a broader sitewide issue

@argos1873 is your league still having issues?  I went through them all and found one more, I believe everyone that was affected should be fixed now.

**Comment by mdryden** [comment]
Thanks @Beavers22  - I have fixed this for your league now.  Might be a clue as to why this happened.  Sorry for the trouble.

**Comment by argos1873** [comment]
> > My league has the same issue, I think it might be a broader sitewide issue
> 
> @argos1873 is your league still having issues? I went through them all and found one more, I believe everyone that was affected should be fixed now.

Yes it's been fixed, thank you!!
