### ISSUE TITLE
Terry Godwin

### ISSUE THREAD

**Issue by mwk537** [110yards/fantasy#217]
Hamilton has him starting tomorrow at wide receiver and I can’t find him on the site. Appears he joined the cfl in early September. Can we get him added as he starts tomorrow night?

**Comment by bohsask** [comment]
It would be good to have him added as he is definitely a starting receiver this week. Is this another case where the CFL's own data is the problem?   He does have a CFL plays page... https://www.cfl.ca/players/terry-godwin/167336/

**Comment by mdryden** [comment]
Closing this ticket as a duplicate of #218, where more details can be found.
