### ISSUE TITLE
Questions before we do our draft today

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#22]
Good morning and thanks again for opening this up for us to use.  It is huge and much fun has already been had in our chat room.

Questions from newbie;

1. When the draft starts can each person select from their screen or does the commissioner have to make the picks?
2. When people are picked do they hid on the draft list?
3.  After the waiver wire is closed can adds and drops be made?  Or are waivers all controlled via the bids process weekly?

Thanks,  

Thanks, David

**Comment by mdryden** [comment]
I think I answered this one for you on reddit or by email, but just in case, and so others can see:

1) You can either use a snake draft, and let users pick, or a commissioner draft and require the commish to pick.
2) When players are picked, the name of the owner will show up next to their name and they can no longer be picked by other owners
3) The waiver wire only applies for 24 hrs after the last game of the week (starting at 6am the next day).  After the waivers are completed, all players are fair game, first come first serve.
