### ISSUE TITLE
Is 2023 Happening?  

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#226]
Hi there, is 2023 happening?  Sure hope so.  We are getting ready to schedule our draft.

Thanks, David

**Comment by kamikazecanuck** [comment]
Yes, it's time to start asking those questions again!  What are the key dates for the site?  Like when can we draft?

**Comment by mdryden** [comment]
Yep, 2023 is happening.  I hope to have the site rolled over to 2023 this weekend.  You can draft any time after that, though I'd wait until closer to the start of the season.

**Comment by mdryden** [comment]
And we're back!

**Comment by kamikazecanuck** [comment]
Cool!

**Comment by kamikazecanuck** [comment]
Just wondering what happens when you push the "Start 2023 Season" button?  Does it go into draft mode?

**Comment by kamikazecanuck** [comment]
Also, just noticed that my championship game falls on Week 18 which is a triple bye.  Can I adjust the season length?  Is that the kind of stuff that's available after pressing the start button?

**Comment by kamikazecanuck** [comment]
Nevermind.  Just answered my own question by pressing the button.

**Comment by mdryden** [comment]
For anyone in the future, you can adjust the league settings until the draft starts.  If you need to adjust something after the draft has started (but before it's completed), you can undo all of the picks, reset the draft to unstarted, and then make your changes.
