### ISSUE TITLE
Is a SB considered a RB?

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#229]
Is an SB considered an RB?

Could we use OF as a SB and still have a RB?

Thanks, David

**Comment by mdryden** [comment]
I can actually post you the code on this one :)

https://github.com/mdryden/110yards/blob/main/yards_py/domain/enums/position_type.py#L88

Player positions come directly from the CFL, so player positions may change through the season, or not perfectly match how players are actually used by their team.

Slot backs are mapped as receivers on the site, so they can be placed anywhere a receiver can be placed, meaning Receiver, Offensive Flex or Flex pots.

So yes, you could have a slotback and a running back on the roster at the same time.

**Comment by davidkinetisense** [comment]
What about a fullback?  Are they RB?

**Comment by kamikazecanuck** [comment]
FBs are considered RBs
