### ISSUE TITLE
The Canadian Flag does not seem to be accurate

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#232]
How are Canadians determined?  The maple leaf does not seem to be accurate.

![image](https://github.com/mdryden/110yards/assets/64800266/61a46a8c-bf6f-47f5-b2eb-1e6f97068a57)

**Comment by mdryden** [comment]
It's based on the CFL's definition in the API of a foreign or non-foreign player, which I believe follows the ratio rules.

**Comment by mdryden** [comment]
It may be more accurate now, though it no longer follows the CFL's loose definition of who counts to for the canadian ratio.  Players who have a birth country of Canada are now the only ones marked with the flag.
