### ISSUE TITLE
Schedule updating

### ISSUE THREAD

**Issue by Tduns4** [110yards/fantasy#233]
I’ll keep this short and easy. I have an 8 man league, and set our playoffs to begin on week 19. The problem with this is that championship weekend is week 20, and there are only 3 games (6 teams). 

This will result in top players not being available in the finals. Was wondering if there was a way to adjust my playoff schedule?

**Comment by mdryden** [comment]
Did you already draft?  If not, you can adjust the end date of your league in the settings.  If so, you'd have to start a new league to adjust it.
