### ISSUE TITLE
Sadly this is what I got from my email I sent to CFL

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#235]
"Hi, David –

Thanks for reaching out. The league is currently overhauling the entire stats system including CFL Connect. Going forward, only select personnel will have access to it.
For fans, Gametracker will be ready to go for kickoff and you can follow the stats live.
I hope this helps. Happy to answer any further questions you may have.
Enjoy the season kickoff tomorrow night!

Lucas Barrett"

**Comment by kamikazecanuck** [comment]
Very bad news…

**Comment by annamc604** [comment]
I volunteer to do data entry too!
