### ISSUE TITLE
We had to create a new draft and only 4 people could join....

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#24]
We had to create a new draft and only 4 people could join....

Only 4 people were able to join and it then said the league was closed.  

We need to be able to add 8 players https://110yards.ca/join/t7ZuY500SrPKBkhr1MnU?password=bigballsandfields

Can you test this and see why it is doing this?  We need it fixed before the end of Wednesday so we can start.  Thanks, David

**Comment by mdryden** [comment]
Registration for your league is marked as closed - this happens automatically when you generate a schedule.

You can open the league up to be joined again in the commissioner tools area.

**Comment by davidkinetisense** [comment]
It was my guys not knowing how to sign up.

**Comment by davidkinetisense** [comment]
Closed
