### ISSUE TITLE
Running back issue

### ISSUE THREAD

**Issue by redblacks** [110yards/fantasy#25]
Hey Michael just wanted to thank you again for doing this site we love playing.....just a question   last year we were able to put our second running back in the bye slot     was wondering if you can allow our league for that to happen    we play with a back up running back   ..... for instance  andrew harris is injured this week ill need a second guy on my roster we all drafted 2 guys

**Comment by EElks** [comment]
Hi.  Love the website.  We have the same problem were we could only have one RE on the whole roster and couldn't put one in an Offense Flex position or on the bench.  Thanks again.

**Comment by SkyTown81** [comment]
We have the same issue as well. 
Thanks so much for taking your personal time on devloping this awesome site. We can't thank you enough for making our CFL pools so much easier and smoother. CFL Fantasy GMs thank you!

**Comment by bpak89** [comment]
I have the same issue. Injured Andrew Harris but can't put him in IR and pick up another RB for week 1.

**Comment by mdryden** [comment]
There was a bug initially which didn't properly ignore the IR and BYE slots when adding the 3 limited positions, but this is fixed now.

Anyone should be able to pick up a secondary running back if their main running back is first placed into an IR or BYE slot.

As for Harris, this is an issue with the data source I'm using to set the players' statuses; it's not showing Harris on IR.  I'm working on a fix for that now, you can track the status here:

https://github.com/mdryden/110yards/issues/28

**Comment by redblacks** [comment]
Thanks Michael,     seems to be working fine for the IR slot but the Bye slot is still locked....   any way we can unlock that too so we can put an IR guy in the IR slot  and then our 2nd Running back   in the Bye Slot   and we have a 2nd bye slot for use for roster players on bye Thanks again

**Comment by mdryden** [comment]
No, the bye slot only works for players who are only on bye.  I'd suggest that you set up your league with more than one IR slot if you're hoping to use it this way.

I'm going to revisit the "1 RB per roster" limit next season, but it's pretty ingrained in the site for this year.

**Comment by redblacks** [comment]
our league is set up   any way you you add in an extra  IR slot for us ? REDBLACKSBOYS is league name

**Comment by mdryden** [comment]
Sorry, but it's very hard to change the rosters manually after the season starts.  Chances are high that I'd end up breaking something in your league and I'd rather not risk it.  Sorry :(
