### ISSUE TITLE
Malik Henry Stats Not Appearing

### ISSUE THREAD

**Issue by levinen69** [110yards/fantasy#251]
**Describe the bug**
A description of what the bug happened and what you expected to happen.

**League ID**
Please include your league id if applicable.

**Roster name**
Please include the name of the affected roster, if applicable.

**Screenshots**

**Device information**
Please indicate if you are using a mobile device or desktop, and the browser you are using, if applicable.

**Comment by HoldenCaulfield23** [comment]
In my league this appears to be all players from the Calgary - Saskatchewan game this weekend.

League ID: EAD3AlKPUhx3AvhpiHDd

I'm assuming this is why the week hasn't finalized yet for the week (updated standings and whatnot).  I know the issues going on with API/Stats, so I'm not worried about it but as an FYI.  I appreciate all the work on this site to keep it active.  Much appreciated.
