### ISSUE TITLE
Terry Williams--listed twice

### ISSUE THREAD

**Issue by EElks** [110yards/fantasy#26]
Hi.  I drafted Terry Williams the WR and then saw him also listed as a RB.  He's listed twice.

**Comment by mdryden** [comment]
It appears there are actually two Terry Williams' floating around the league - one is this guy: https://www.cfl.ca/players/terry-williams/162206/, RB for Edmonton

The other is a receiver from Greenwood, MS who appears to have been cut at some point.

**Comment by EElks** [comment]
That's my bad.   Burned that draft pick!!

Thanks for all your effort Michael.   We are six friends/family mostly in
Edmonton and ran a pool based off of the TSN website. It was frustrating
not to draft teams as we followed different players all season.  We're
really happy with what you've done and are looking forward to the season.

If you post something more about your story and the work you've done, we
look forward to reading it.

Matt

**Comment by mdryden** [comment]
Thanks man, I appreciate the feedback and the kind words. Glad you guys are enjoying it!

**Comment by mdryden** [comment]
Thanks man, I appreciate the feedback and the kind words. Glad you guys are enjoying it!
