### ISSUE TITLE
When will the site be ready for 2024?

### ISSUE THREAD

**Issue by daschn2** [110yards/fantasy#265]
**Describe the bug**
A description of what the bug happened and what you expected to happen.

**League ID**
Please include your league id if applicable.

**Roster name**
Please include the name of the affected roster, if applicable.

**Screenshots**

**Device information**
Please indicate if you are using a mobile device or desktop, and the browser you are using, if applicable.

**Comment by mdryden** [comment]
Soon!

**Comment by mdryden** [comment]
Today!
