### ISSUE TITLE
Enhancement Request: My Team page player sorting

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#27]
I have some suggestions for the way the "My Teams" displays.  I think the O-Flex Slot should be under the last WR Slot.  That way all your offense guys are together and can be easily swapped around.

Kicker slot should probably be the last slot of your active players. 
Basically O-Flex and K slots should be switched.

**Comment by mdryden** [comment]
I like this idea.  I think I made the sorting really easy too, but I need to double check.  If this is easy, I'll roll it out in the next few days.

**Comment by mdryden** [comment]
Took a quick look and what I thought would work will not.

I'll revisit this one a few weeks into the season, but it might be a next year thing.

**Comment by kamikazecanuck** [comment]
Sure. Low priority one
