### ISSUE TITLE
Draft not working: Request failed with error code 500

### ISSUE THREAD

**Issue by DaCommish** [110yards/fantasy#271]
**Description**
A description of the question or request

**League ID**
Please include your league id if applicable.

**Roster / Name**
Please include the affected roster name if applicable.

**Additional information**
Screenshots or anything else you think might be useful to help understand the request.

**Comment by DaCommish** [comment]
The site doesn't seem to be working for our draft.

**Comment by mdryden** [comment]
This should be fixed now, sorry for the bad timing.
