### ISSUE TITLE
No game showing for Dalton Schoen 

### ISSUE THREAD

**Issue by levinen69** [110yards/fantasy#274]
I drafted Dalton Schoen and he still appears as a Free Agent. Should I start him tonight/will the stats from today's game count or should I wait until the issue is fixed?

<img width="637" alt="Screenshot 2024-06-06 at 8 00 01 PM" src="https://github.com/110yards/fantasy/assets/136773396/9e11509a-b643-45a6-bd96-ef315a2d0242">

**Comment by mdryden** [comment]
Should be fixed now.
