### ISSUE TITLE
Week 10

### ISSUE THREAD

**Issue by SteveTaskersSon** [110yards/fantasy#29]
First off, THANKS so much for putting in all the work to make this site work!!!  

During week 10 OTT and TOR both play 2 games each.  Just wondering which of their 2 games will be counted in terms of points for OTT and TOR players that we have on our rosters (is anyone really going to draft a REDBLACK?????LOL)

Thanks again!!

**Comment by mdryden** [comment]
Thanks for point this out, I hadn't noticed.

I'll have to put a fix in for this, but the way we did this a few years ago is that players with two games would only get points for the first game.

**Comment by SteveTaskersSon** [comment]
Awesome!  Thanks!
