### ISSUE TITLE
Mobile use issues with league setup

### ISSUE THREAD

**Issue by cstevens780** [110yards/fantasy#3]
Created a private league, copied invite link. The link leads to sign in page which in turn leads to join a league/create league page instead of automatically joining the league. The only way to join the league was to find and cut the league ID out of the join link(league name didn’t work either). It would be nice for the league ID and password to be visible by itself in the commissioner’s tools page, so that can be sent instead. 

Separately please reconsider the passwordless sign on. This process is quite cumbersome for repeat quick sign ins. Especially in mobile where I have to click the link, put in my email, go to my inbox, wait for email, click link which opens a different mail based browser that doesn’t have as many tools, re-enter my email then I am in.

**Comment by cstevens780** [comment]
Also cannot draft for other teams while paused as commish

**Comment by mdryden** [comment]
Thanks for the feedback about the passwordless sign-in.  I may reconsider if there is a lot of pushback, but as a normal guy, I'm concerned about the risk from a possible security breach.

I think (hope) it will be a minor inconvenience as the site stabilizes; it's seems from my testing that you shouldn't have to re-sign in very often.

For the commissioner draft issue, did you notice that you can select the active roster below the player list?  I might need to improve the UI or add some tips, but changing the team in the dropdown changes the team you are drafting for.

While paused, the only option is to undo the last pick, or resume the draft.  You need to make picks while the draft is active.  Only the commissioner can makes pick in that draft mode; the draft is read-only for other users in the league (they can watch but not pick).

**Comment by cstevens780** [comment]
I did an online draft and saw the while paused you can draft for other teams at the top but it still wouldn’t let me which is fine(even if I changed teams at the bottom). I just moved tabs back and forth picking for either team, this isn’t something that should ever really come up I would imagine (unless one or two players can’t make the live draft and the commish wants to pick for them). 

I understand your point on the security of passwords. It’s just a few extra steps and I likely wouldn’t regularly have 20 login emails in my email from normal use. 

Are the rosters supposed to show after a draft is completed at this point in development? I can’t seem to find them on any of the pages. Also when looking at the players page I cannot get the FA button to work. It just greys out. 

This site is going to be great, I can’t wait to get the guys together and give this a real go!

**Comment by mdryden** [comment]
No I haven't finished the roster pages yet.  Pretty much the next thing on my list.

**Comment by mdryden** [comment]
Oh, and I'll try the commish draft again see if I can figure out what you're having issues with.  I think it's working correctly and just confusing, but it could be a bug too.  Either way I'll need to make it easier it seems.
