### ISSUE TITLE
Total Points not adding up correctly 

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#30]
Hopefully just a visual thing but when you go into your team and add up all the points it doesn’t equal the total that’s displayed in the matchup for any team. It’s affecting every team in my league right now.

**Comment by mdryden** [comment]
Yep, I just noticed this as I was combing through our league as well; you beat me to the bug ticket.

I found the bug, just testing a fix now and I will recalculate everyone's scores.

**Comment by mdryden** [comment]
This should be fixed now, if it still looks wrong please let me know so I can take another look tomorrow.

**Comment by davidkinetisense** [comment]
Hi, Hamilton Wr Acklin has different points in two league.  One says 15 and one says 20.  Can you confirm why it is different.

**Comment by mdryden** [comment]
Hmm, that's not good.  Can you give me the league ids?  I may not get a chance to look for a day or two but I'll make sure it's fixed before the end of the week.

Also, if it's a recent score change, it could just be a delay; it takes a bit of time after scores update for things to spread out to all leagues.  It might work itself out.

**Comment by mdryden** [comment]
I'll close this issue and track the mismatch issue here: https://github.com/mdryden/110yards/issues/32
