### ISSUE TITLE
Week 1 note: Waivers will be run manually this week (and possibly next)

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#33]
To help ensure that nothing goes horribly wrong during waivers this week, I will be running some of the tasks manually.  This means that waivers may start early and end early, or possibly late.

My goal is to start waivers manually on Saturday evening, the process them Sunday evening, however life is busy this time of year and my plans go awry.

Once enabled automatically, the schedule will be:

7am (eastern) after the last game of the week completes, the matchup results will be calculated, wins and losses updated, and the week will switch.  At this time, players will be unlocked and available to bid on.

7am one day later waivers will be processed and players will be freely available.

**Comment by kamikazecanuck** [comment]
Seems like you’re only giving 8 hours for the week to resolve. That makes me nervous because it seems like the league itself takes 24-36 hours to do their own reconciliation.  You may get some complaints about stats not matching up especially for the last game.

**Comment by mdryden** [comment]
That's fair; I'm not married to this schedule, it's easy to change.  The tricky part really is that the start and end of the CFL week isn't fixed like the NFL, which means if I give more time after the last game, sometimes it's a short window for processing waivers and free pickups if the next week starts early.  (Think labor Day weekend if there's a Monday and a Thursday game)

Plus from a personal standpoint, I think it's nice to see the matchup results the next day, and start working on your roster changes right away.  That's generally how NFL leagues work, but maybe the NFL is quicker at stat corrections.

Maybe I'll look into keeping track of when and how the games change; it might be nice to see how long the corrections generally take.

**Comment by kamikazecanuck** [comment]
I get that and this year will probably be an even stranger schedule. 

In my opinion though nothing is more important than the stats and points integrity. When a Poolie looses a close game and he sees that the Fantasy site only gave his player 2 sacks but it says right there on CFL.ca he got 3 sacks and that’s the difference literally nothing else matters. Like the second most important software issue will be like 2% as important to him as this stat discrepancy.  Definitely Free Agent time is nothing compared to that.  It just makes everyone lose faith in the website and I’ve had people quit over it actually in years gone by. 

Anyway, keep up the good work. Everyone enjoying having Fantasy CFL back so far.

**Comment by mdryden** [comment]
Yea it's a tough line to draw.  Stat corrections can happen any time, and while you do want the scores to be accurate, you also can't wait a week to be certain.  And you definitely don't want to change a matchup result once the next week has already started.

I'll go through the schedule with a fine toothed comb and see what makes sense.  At a glance, it's looking like I might need to make different rules for different weeks.

For most weeks it looks like if I allowed ~36 hrs, there would be lots of time for 24 more hours of waivers.

Week 8/9 looks bad though.  Week 8 ends on a Friday and week 9 starts on a Tuesday.  Still might be ok though.

In any case, I'll wait until tomorrow night (Sunday) to close this week of.  Longer if I run into any issues.

Going forward I'll establish a schedule and post it so it's clear.

**Comment by kamikazecanuck** [comment]
How does it work if you bid on more players than you have open slots?  Say you have 2 open slots, bid on 3 players with no drops.  If the first 2 go through then the 3rd one is just invalid? Or conversely you don't win the first one the next two go through?

**Comment by mdryden** [comment]
The 3rd bid will fail.

Each bid is evaluated on a few criteria:

1) Is it the highest bid

2) If there's a tie, does this bid have the tie break?

2) Does the manager have enough money for this bid?

2) Is there a drop player for the bid, and is that player still on the roster

3) If there's no drop player, is there space on the roster?

In your scenario, the two highest value bids (or earliest, if they are the same value) would be processed first.  Assuming they both win, then the 3rd would fail with the reason "Drop player not on roster"

**Comment by mdryden** [comment]
Waivers for week 1 are complete.

I've added [this ticket](https://github.com/mdryden/110yards/issues/36) to improve the transaction messages that go along with waiver claims.

I have a way to review post-week waiver claims, so if anyone has a question on why they did or did not win a waiver claim, feel free to ask (include your league ID please).

**Comment by bohsask** [comment]
What time will waivers typically process on the site?  Early morning?

**Comment by mdryden** [comment]
I'm still doing them manually currently, but once I'm confident things are working properly the plan is for results to be calculated at 7AM, the day after the last game of the week (eg: if the last game is Saturday night, results are calculated Monday at 7AM EST) - this allows 24 hrs for any final stat corrections to come in from the CFL.

Waivers then run for 24 hours after that, and process at 7AM the next day (Tuesday, in that example).

**Comment by mdryden** [comment]
Ran them late this week, sorry everyone.

The process looks stable now though (🤞) - so I'm enabling the automatic job.  Results should now be calculated at 7AM EST, a minimum of 24 hours after the start of the last game (eg: if the last game is 9PM on a Saturday, results will be calculated at 7AM on Monday morning).  Waivers will be processed at 7AM the following day.
