### ISSUE TITLE
Player points not calculating and wpg stats not showing 

### ISSUE THREAD

**Issue by BigCalster** [110yards/fantasy#34]
Doing our draft tomorrow. Player points are not showing up even though stats are. However, Winnipeg player stats & points are not showing.

**Comment by BigCalster** [comment]
![image](https://user-images.githubusercontent.com/88637481/128655174-a9db907b-eafe-4b61-9202-2a27c2154635.png)

**Comment by mdryden** [comment]
This will happen soon - when the week ends, the matchup results are calculated, and so are the player season scores.

The Collaros thing is weird, though, I'll take a look at him and a few of the other players to ensure there isn't a bug there.

**Comment by mdryden** [comment]
Hmm - so you might have uncovered a bug here - I'm guessing you started your league after the winnipeg game ended?

Need to confirm a few things.  if you haven't done any matchups yet, it shouldn't hurt your league going forward, but I'll see what I can do to make sure Collaros and other WPG player stats show up properly for you.

**Comment by mdryden** [comment]
@BigCalster - can you post your league ID here please so I can take a look?

**Comment by BigCalster** [comment]
I had the league created before the winnipeg game, but knew we weren't going to draft until after week 1. I may have start/reset the draft a couple times to see how it worked. 

RGK86NDDzepRZRxAz2iV

**Comment by mdryden** [comment]
I think I have the WPG stats thing fixed - look ok?  They were the first game of the week and I did have to do some bug fixes.

**Comment by BigCalster** [comment]
Looks go to me. Thanks for doing that! By the way, the site is great. Excellent work. Really been missing CFL Fantasy the last few years.
