### ISSUE TITLE
Standings not in order

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#35]
The league Standings aren’t in descending order of awesomeness. I didn’t make a 4th quarter comeback to be at the bottom of the list!

**Comment by mdryden** [comment]
Fixed this one last night.

**Comment by kamikazecanuck** [comment]
Thanks. This is may be my only chance to be in the top half of the standings….

**Comment by mdryden** [comment]
I liked it better before, I was 1st instead of 5th.
