### ISSUE TITLE
It would be nice to see how much players paid for winning waiver bids

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#36]
Right now, it just shows "Team name added Some Player".  For adds that happen via waiver claim, this message should include the amount as well, eg "Team name claimed Some Player ($10)". This would only apply to winning bids (losing bids would remain hidden), and only after waivers are done for the week.

It's too late for waivers this week, but I'll have this out for next week.

**Comment by kamikazecanuck** [comment]
Yes, that would be good.
