### ISSUE TITLE
League History

### ISSUE THREAD

**Issue by bohsask** [110yards/fantasy#37]
Just curious, is the draft history (who was drafted in what position) saved anywhere in your database for a league? After we finished our draft (which worked great btw) I didn't get a chance to copy the list from the draft window.  We will likely run a keeper  league next year so it  would be really nice to keep a copy of who was drafted where for that reason.  If it's not possible let me know and we'll try to piece things together.

**Comment by mdryden** [comment]
Yes, it's saved.  I will create a page which you can use to see the draft results at some point this year.

**Comment by bohsask** [comment]
Absolutely no rush on this one whatsoever, great to know it's saved.

**Comment by kamikazecanuck** [comment]
Or an end of year roster list. Needed for keeper league.

**Comment by mdryden** [comment]
I've decided to expand on this one a bit and add a new feature for League History. (I've alluded to this one previously, and have decided it's next on the list).

It will work like this:

When the season ends, a season snapshot is already saved with the league.

If a league renews, then those snapshots will be available to view from the league homepage.  You will be able to view the final standings, as well as the draft picks and final rosters.

TBD whether it makes the cut right away, but it's also my intention to allow the manual creation of prior league results, so if you have a long-running league like mine, you can enter past results and keep track. (This will just be standings, not draft picks or rosters).

**Comment by kamikazecanuck** [comment]
That’s great. We are a dynasty league too. Coming up on 7th year. It would help if there was some way to carry over rosters but still have a draft to fill the gaps.

**Comment by mdryden** [comment]
For this year I think the best I can offer is the ability to see the final rosters from last season, but I do hope to have full support for keepers in the future.

**Comment by bohsask** [comment]
Thanks for the work you put in on this in the offseason, love the enhancement made thus far!
