### ISSUE TITLE
Points on My Player page sticky

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#39]
This one's hard to explain but I've noticed that the points on the My Team page don't move even if you move around the player.  For example if within your own roster Player A has 10 points and Player B has 5 points if you swap them they points attached to the player do not move.  I believe this also happens with pickups and drops.

**Comment by mdryden** [comment]
Ha, interesting.  I noticed today at lunch that I had forgotten to zero out the points for each roster position at the end of the week, amusing that it ends up making it look like player scores are wrong.

A fix is coming shortly which will reset each slot on the roster to zero at the end of the week.
