### ISSUE TITLE
Lineup Page

### ISSUE THREAD

**Issue by bohsask** [110yards/fantasy#41]
This is an enhancement request.   On the "lineup" page, would it be possible to show a few more pieces of player information, perhaps similar to the view that is available on the "players" tab.  For example, position would be great to have here, if you're not that familiar with a player, it's not obvious what position players listed in the bench and flex spots are.  A couple more stats to inform roster decisions could be handy here too (i.e. avg. points, GP).

**Comment by mdryden** [comment]
Totally agree, I've been working on this one for a few days now (a few things were rushed in order to make the start of the season).

Here's a sneak peak at what's coming soon:

![image](https://user-images.githubusercontent.com/5611490/128913698-23e9ffa3-e458-4c07-8f05-f3c91b5a1a59.png)

**Comment by bohsask** [comment]
Looks great, thanks.

**Comment by kamikazecanuck** [comment]
Much better.
