### ISSUE TITLE
Enhancement Request: Commissioner Controls

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#42]
IMO Commissioner needs control over GM's rosters ASAP.  Especially now that IR slot is on "honour system."  Sometimes that doesn't work out.  Commissioner needs to be able to cut players to prevent shenanigans.

**Comment by mdryden** [comment]
I'll start on this soon, but it won't make it this week, so tell your players to get their shit together ;)

**Comment by mdryden** [comment]
That said, I'm hoping to trial a fix for the IR issue this week.  I won't disable the honor system IR until it's had at least a week of testing, but it may be temporary at least.

**Comment by kamikazecanuck** [comment]
Thanks. Actually I prefer the honour system with Commisoner axe. It actually causes less problems usually

**Comment by mdryden** [comment]
Interesting.

It's my intention to do away with the honor system once I have a working solution, but perhaps I'll make it a league option for 2022.

**Comment by kamikazecanuck** [comment]
Well if you put a player on IR legitimately what’s to stop him from keeping that player there after he’s not injured? That player can not be dislodged right? Still need commissioner powers.

**Comment by mdryden** [comment]
Thinking I'll be able to start on this one tomorrow.  What functions are you thinking about?

I've seen "change team name" and "force drop a player".  Anything else you think a commissioner should be able to do?

**Comment by kamikazecanuck** [comment]
Change scoring if possible. When a Commish makes a roster move the move log should reflect it was commissioner.

**Comment by mdryden** [comment]
I'll allow scoring changes, but keep in mind it won't be retroactive.  I might also block it while games have started for the week.

**Comment by mdryden** [comment]
https://github.com/mdryden/110yards-api/issues/89

**Comment by kamikazecanuck** [comment]
I don’t know about prevent future name change. Usually, changing it gets the message across. Other commissioners probably don’t want to get notifications that someone is changing their name.

**Comment by mdryden** [comment]
It's a separate option.  I figure if someone is being a problem (say, in a public league), you might want to set their name and then block them from future changes.

Not required to be used, and it's not directly tied to the name change feature, i just thought it might be useful.

**Comment by bohsask** [comment]
If you're still looking for ideas on commissioner controls etc, and how to force GMs to remove ineligible players from the bye week/IR slots - yahoo and espn leagues don't let you add any new players if you've got an ineligible player in a slot.  Don't know how hard that would be to implement...  But it forces you to make things right without a commissioner intervention or involvement  which I think is preferrable.

**Comment by mdryden** [comment]
This is a good idea, thanks.

**Comment by mdryden** [comment]
I've created another ticket for the potential "ineligible roster" behavior, as bohsask suggested, but I think it will probably be a next year feature (possibly later this year though).

The feature discussed above are now complete and released to live.
