### ISSUE TITLE
New Roster and Lineup UI

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#44]
This was already released - if you have any issues, please add them here.

**Comment by mdryden** [comment]
From Kamikaze:

"Can't cut players on mobile" (this applies to desktop too).

Fix:

I missed this function in the updated design, but I released it before work this morning.  If you can't see the option, try refreshing the page. I do find that in Chrome, it often takes some time to see the new version of the web page show up, due to some caching that Google uses.  When you click the position button, you should see some new options:

![image](https://user-images.githubusercontent.com/5611490/129219128-91ebb0ac-4bef-4cf1-ab69-d6a84f9b831e.png)

**Comment by mdryden** [comment]
Also from Kamikaze:

"Adding doesn’t work if the guy you want is on your bye slot."

Seems to be working for me, I was able to move a player to the bye slot, then drop him directly from there.  Or am I misunderstanding the issue?

**Comment by kamikazecanuck** [comment]
Mine doesn’t act that way. The X appears on the right side instead of over the blue button. Will wait an hour and see if it updates.

**Comment by mdryden** [comment]
Yea I'd say you're getting hit with the caching problem.  Chrome seems to do it's own caching and I haven't found a way to manually force a refresh on mobile like you can on desktop.  The only two work arounds I know of to make it work right away are to use another browser (eg: Firefox), or to open in Incognito/Private mode.  The second one is a bit annoying because of the log in model.  Rest assured it should show up eventually.

**Comment by mdryden** [comment]
I'm thinking it's a bit hard to differentiate active positions from bench and reserve positions.  

- [ ] Add some color or spacing to improve this.

**Comment by kamikazecanuck** [comment]
It's working now.  I notice sometimes it takes a couple hours for your fix to go though.

**Comment by kamikazecanuck** [comment]
> I'm thinking it's a bit hard to differentiate active positions from bench and reserve positions.
> 
> * [ ]  Add some color or spacing to improve this.

Ya I think before there was a slight bigger space between the scoring and non-scoring players.  Maybe just  line dividing the two?

**Comment by mdryden** [comment]
> It's working now. I notice sometimes it takes a couple hours for your fix to go though.
