### ISSUE TITLE
Yamasaki

### ISSUE THREAD

**Issue by Flaccoseagulls** [110yards/fantasy#48]
We play with 4 pt FG, 2pt miss FG and rouges 

Yamasaki scoring as 9 pts it should be 7?

Miss FG for rouge, two made FG, one miss

+1,+4,+4,-2 = 7

**Comment by mdryden** [comment]
You can see how the score is calculated for your league by viewing his player page and clicking the question mark beside the score for this game.

Maybe your league scoring is different that you realize?

If not, please share your league id

**Comment by mdryden** [comment]
I think you're right, I found a bug.  Seems like field goal misses aren't being counted properly.

**Comment by mdryden** [comment]
His score should be fixed now for your league, and his miss count in his game log should be correct for last week as well.

I'm not going to apply this correction retroactively, if anyone had a league with Yamasaki or Boris Bede (the only kickers to miss last week) on a roster that won last week, and the incorrect calculate would have changed the outcome of the match, please contact me.
