### ISSUE TITLE
One of the guys Windows computer and Android phone is not connecting to the site.  “Err_Connection_Closed” error

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#5]
One of the guy's Windows computers and Android phone is not connecting to the site.  Connect showing up as not secure.  “Err_Connection_Closed” error

https://www.webnots.com/how-to-fix-error-connection-closed-error-in-google-chrome/

I have tried all the troubleshooting that I know other than having you look at your side.

**Comment by mdryden** [comment]
There was an issue with the DNS configuration for the live site which has now been resolved.  If anyone is still seeing this, please let me know.

**Comment by davidkinetisense** [comment]
Thanks this is now working for those experiencing the problem.
