### ISSUE TITLE
Activity Log appears to be in Japan Time Zone. We are in Mountain Time Zone.

### ISSUE THREAD

**Issue by seanarobertson** [110yards/fantasy#50]

**Comment by mdryden** [comment]
There was a bug in a earlier release of the site which tagged the transaction times incorrectly.  That should be fixed now though, so if you're seeing time errors on new transactions please let me know what your League ID is.

That said, the transactions are saved in the database as UTC, and should be displayed in the local timezone according to how your browser is configured.
