### ISSUE TITLE
Schedule until week 17, reality until week 16. 

### ISSUE THREAD

**Issue by Mic161** [110yards/fantasy#54]
I Made a League with some friends, and we are on a der schedule now. We have 4 players for the playoffs, and 2 playoff weeks. The Last possible Option was to start the playoffs in week 16 so we chose to take that. And i know, its Kind of selfmade bc there is on week 17, and now we her shown:
Week 1-14 reg season 
Week 15 nothing 
Week 16 Playoffs 
Week 17 Championship 
Does that mean  we will have 1 week off, then 1 week playoffs and they a Championship without points? Or will week 15 just be called week 16 and week 16 week 17 in our league?

**Comment by Mic161** [comment]
If it would Maybe be possible to change the beginning of the playoffs Even if the draft is Already made, or if you could change it Manually in our League, you would help us so much. Would be sad if our First cfl Fantasy season stops because of our dumbness. :/

**Comment by kamikazecanuck** [comment]
Hmmm, now that I look at it my league has 5 games for the 1st week of the playoffs.  Pretty sure there's something wrong there as well.

**Comment by mdryden** [comment]
Hmm.  I'll take a look at both of these issues.

**Comment by mdryden** [comment]
@Mic161 can you post your league ID?

**Comment by Mic161** [comment]
fN50LVnlaxU3A5Z9H9dX

**Comment by mdryden** [comment]
That is really weird - I definitely see the problem here.  It's probably going to take me a bit to resolve this problem (got my hands full with this scoring stuff right now), but I'll have it fixed for you in a couple of weeks at the latest.

**Comment by mdryden** [comment]
@Mic161 - your league should be fixed now.

@kamikazecanuck - the issue with your league isn't really an issue, it's just kind of weird how it's displayed.  I'll work on a fix with the playoff stuff I still need to do in that other issue.  In your case though, the 5 matchups are:

2 playoff matchups
2 playoff byes
1 loser matchup

Once the playoff matchups are generated, you'll see those two matchups show up as byes.

**Comment by kamikazecanuck** [comment]
2 playoff byes? Meaning 2 teams have a bye right?

Ok thanks. Figured it was just a display issue.

**Comment by mdryden** [comment]
Right - your league is configured for top 6 + loser game. Your matchups will be:

1 - bye
2 - bye
3v6
4v5
7v8 (loser game)

Winners of 3v6 and 4v5 will move on to play 1 and 2 (1 gets the lower winner)

**Comment by kamikazecanuck** [comment]
Cool. Thanks again.
