### ISSUE TITLE
Week 10&11

### ISSUE THREAD

**Issue by Mic161** [110yards/fantasy#55]
So, After week 10 Toronto will Play hamilton, who both don’t Play in week 11, ergo toronto will have 2 Games in week 10 and None in week 11. will the hamiltonvstoronto Game be Counted as week 11? Feels like it would make More Sense.

**Comment by bohsask** [comment]
You'd know prior to setting your week 11 lineup how many points your toronto players ended up with though.  If you could somehow lock the rosters with the understanding that if you starting a toronto player in week 10 you're also starting him in week 11 it could work.  That gets complicated.

**Comment by Mic161** [comment]
> You'd know prior to setting your week 11 lineup how many points your toronto players ended up with though. If you could somehow lock the rosters with the understanding that if you starting a toronto player in week 10 you're also starting him in week 11 it could work. That gets complicated.

Or you have to make your week 11 Roster until monday Morning
