### ISSUE TITLE
Enhancements - User name, player lists

### ISSUE THREAD

**Issue by bohsask** [110yards/fantasy#56]
The site is working awesome.   A couple of enhancements our group has talked about to consider for the future

-Can the 'user name' be displayed somewhere alongside the 'team name' on the team pages.  With people changing their team names frequently, it can take some sleuthing to figure out who you're playing currently.  Maybe we're just weird and are only ones where creative team names based on players you have rostered ant the Gm you are playing against are part of the fun.

-Can the players own team be added as a column in the player pages.  Then you could sort by team if you're just looking for say Saskatchewan receivers.  The team graphic beside the player name is cool too but especially during the draft people were wondering how to just isolate one team in players in the list.  

-On the player page, if you hit the back arrow in the browser after clicking on a player, it loses all of the filters and sorting you had set up.  Say you're looking at a list of free agent DB's and you click on one to see the game log, then go back to the list to add him or look at another player, you have to  search for him or set up the filters again.

-

**Comment by bohsask** [comment]
Another stats column suggestion to add in the player lists would be the total number of points gained "last week".

**Comment by mdryden** [comment]
These are good suggestions - I've split them all out into their own feature requests.
