### ISSUE TITLE
Players in Postponed games are now treated like they are on bye

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#57]
I naively thought we could make it through the season without cancellations but I guess not.  Seems like we should do something for them, like make those players count as having the "bye" status?  Wish I had put more bye slots in my league too.

That seems like the easiest workaround but I don't know.  A postponement slot is probably way too complicated.

**Comment by mdryden** [comment]
Yes, I'm going to put something together to allow those postponed players to be placed on bye.

If they get a game later, and it ends up as a double week, then it will require another fix I suppose.  Same as for week 10.

Fingers crossed that the site doesn't go haywire this week, lol.

**Comment by mdryden** [comment]
This was rolled out this morning, it should be possible to put Edmonton and Toronto players into bye slots now.

**Comment by kamikazecanuck** [comment]
Thanks!

**Comment by EElks** [comment]
Thanks for this Michael--any chance we could adjust the league settings and add another bye slot to our fantasy league?  With three teams now on the bye this week, some fantasy teams have three players on the bye.

**Comment by kamikazecanuck** [comment]
Candidate for future commissioner power: adjust roster settings.

**Comment by mdryden** [comment]
Sorry @EElks, changing the roster after the season starts isn't supported and doing it manually is more likely to break something than to be helpful.  Do you guys have IR slots you could allow players to use temporarily?

Here's hoping this is a one-week thing.

As an aside, giving the commissioner power to adjust the results of a matchup is on my radar for this season.  If nothing else, you could potentially throw away the results of this week, once I roll that feature out.

**Comment by EElks** [comment]
Good to know in all fronts.

We do have one IR spot for each team.  I wish I would have made this two,
but it's too late for that!

Being able to scratch a week would be nice, but we were planning on
counting every week.

Thanks again for your efforts.

Matt

**Comment by kamikazecanuck** [comment]
4XVWS3uyiwxXU4BAg0S7

My main concern is 1 of 3 screens says I lost my game. Hoping the site goes with the other 2….
