### ISSUE TITLE
League Tweaks 

### ISSUE THREAD

**Issue by Shazzawinestain** [110yards/fantasy#58]
Hi there, I'm the commissioner for my CFL league and we're hoping to tweak two elements of the Roster. "A League of their Own"
1. Increasing BYE spots from 2 to 4 
2. Adding a Defensive Flex spot from 0 to 1

Please let me know if you can assist! Thanks.

**Comment by mdryden** [comment]
Sorry @Shazzawinestain - it's not possible to change the position configuration after the league has started.
