### ISSUE TITLE
Points off

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#59]
Haven’t checked everyone but Sean Thomas Erlington’s points seem to be way off.

**Comment by kamikazecanuck** [comment]
I wonder if it’s drawing the wrong week for the total? When you click his name it says the correct points he should have for this week but not for the game page.

**Comment by kamikazecanuck** [comment]
And Simoni Lawrence

**Comment by kamikazecanuck** [comment]
And Ahmed Thomas

**Comment by kamikazecanuck** [comment]
Also the scoreboard page with all the scores doesn’t match the game page head to head score. Probably more of a visual thing.

**Comment by SteveTaskersSon** [comment]
HAM WR Jaelon Acklin is also off.  He only got 13 yards but that will make a difference in a game in my league where the difference in score is 0.15.

**Comment by kamikazecanuck** [comment]
> HAM WR Jaelon Acklin is also off. He only got 13 yards but that will make a difference in a game in my league where the difference in score is 0.15.

That’s weird. He’s correct in my league.

**Comment by mdryden** [comment]
Sorry, just catching up on this.  Can you guys send me your league links again?  I don't really see how this is possible but I need to investigate.

That said, what you see on player pages is going to be the actual value used during the end of the week calculations.  All of the other spots are just calculated from those values.  I'm not sure how it could happen, but in theory I suppose it's possible for one of those to have been thrown off.

**Comment by SteveTaskersSon** [comment]
Here's my league ID:  lYng6GUUiaL4MiMsdbai

I think I see what you're saying.  When I click on Jaelon Acklin to bring up his game log his score does read as 1.3 for this week.  But on the week 4 matchup screen his score still shows up as 0. 
I also noticed that Darnell Sankey also reads 6 points in his game log but the week 4 matchup screen he only has 4 points.

**Comment by kamikazecanuck** [comment]
4XVWS3uyiwxXU4BAg0S7

My main concern is 1 of 3 screens says Iost. Hoping the site goes with the other 2…

**Comment by bohsask** [comment]
xDTpKTT4DRK3MAf4PLSD

What we're seeing is the scores calculated on the individual 'my team' pages appears to be correct, but the summary scores on the 'league' page don't match in a few cases (off by ~20 points in one case).

**Comment by mdryden** [comment]
Thanks guys, results have been calculated for the week, but it's easy enough to re-calculate if there's a mistake.

I'm working on a fix for this bug, but I believe it's visual at this point.  The way the scoring works currently kind of "floods" the sites with updates, and it appears that it's possible for things to end up slightly out of sync.

-----

Edit:

Unfortunately it does appear that some results were affected.  I believe that the correct scores appear on the My Team and VS pages, but occasionally end up out of sync on the home page and on the league index (this is the "matchup" object).  Further, it also appears that this matchup object is what I'm using the calculate W/L.

I am working on a fix right now for this.

Results for this week and previous weeks will be recalculated.

**Comment by kamikazecanuck** [comment]
My game was incorrectly resolved. It was only incorrect on what I call the scoreboard. It was correct on My Team and the head-to-head matchup screen.

**Comment by mdryden** [comment]
This has been resolved now.  All weeks have been recalculated, and I can confirm in your case, @kamikazecanuck, your matchup result has also been corrected.

I have a follow up fix to release at some point this week which will resolve the out of sync problem, but going forward the results should always be calculated from the roster score, which was correct.

**Comment by SteveTaskersSon** [comment]
In my league the problem continues.  Jaelon Acklin still doesn't register any points (should be 1.3 in our league), and Darnell Sankey is still 2 points short.  These 3.3 points are the difference between a win and loss in said game.  

<img width="1440" alt="Screen Shot 2021-08-31 at 8 32 08 AM" src="https://user-images.githubusercontent.com/88464452/131511787-c2a829a5-0a10-4142-b43c-a32bac665553.png">

**Comment by mdryden** [comment]
Damn.  Ok Steve, thanks for the update.  I was hoping to avoid a full recalc of all player stats but it's looking like I may have to do that.  I'll keep you posted.

**Comment by SteveTaskersSon** [comment]
Sorry for the added work...

**Comment by mdryden** [comment]
Don't be sorry, this shouldn't have happened to begin with.

**Comment by kamikazecanuck** [comment]
Thank you. The immediate problems seemed fixed for my league.

**Comment by mdryden** [comment]
This should be fixed for real now, Steve.  Mr. Scoregasm should be much happier that he's not 0-4 ;)

All leagues have been fully recalculated, all the way back to week 1.

**Comment by SteveTaskersSon** [comment]
Awesome!! Thanks!

**Comment by scoregasm** [comment]
I am very happy my pathetic excuse for a team can win by 2 points against a team with no QB lol
