### ISSUE TITLE
Signed up user has two spots in the snake draft.

### ISSUE THREAD

**Issue by seanarobertson** [110yards/fantasy#6]
I would like to be able to edit the snake draft. There are multiple entries for one user.

**Comment by mdryden** [comment]
This might be related to #4 - can you share the link to your league so I can take a look?

**Comment by seanarobertson** [comment]
https://110yards.ca/commissioner/c4fnEgDHs1MKdsnvPTNm

**Comment by seanarobertson** [comment]
It is when I go to draft order in Snake draft mode that I have a blank and a double team.

**Comment by mdryden** [comment]
Thanks for reporting this, as noted in #4, I found a bug that happened if you remove a team from the league, then they (or someone else) join again.

Anyone that runs into this problem will see an alert like this in the draft order tab of the commissioner tools:

![image](https://user-images.githubusercontent.com/5611490/125533004-290e2f7e-539c-4fa2-8fbb-f6f48e749ad3.png)

Clicking update will resolve the problem.
