### ISSUE TITLE
Montreal stats disappearing

### ISSUE THREAD

**Issue by DamonB88** [110yards/fantasy#60]
My montreal players (Adams, Wieneke, etc) stats are all wonky. They only show the last week's points but average out over total games played, so averages are all sewered. Not a big deal but thought I'd point it out.

**Comment by mdryden** [comment]
This should be fixed now too.  Not sure how it happened, need to investigate more.

**Comment by mdryden** [comment]
This is the same issue as #65 (this one came first, but the other one has more discussion).

I think it's an issue with players who get updated while they are on IR.
