### ISSUE TITLE
Player’s Points not Available 

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#61]
Before when you clicked a player it showed his points by week. That doesn’t seem to be working right now. Not that big a deal because there’s a link to their CFL page but having the points based on your league scoring one click away saves so much time.

**Comment by mdryden** [comment]
I must have broke the player page during my update the morning.  I'll take a look.

**Comment by mdryden** [comment]
Should be ok now.  Might take a bit to show up on mobile.

**Comment by kamikazecanuck** [comment]
Seems to be working. Thanks.
