### ISSUE TITLE
Mike Jones DB

### ISSUE THREAD

**Issue by gorillatrain** [110yards/fantasy#62]
Mike Jones DB, Winnipeg Blue Bombers is showing up as no game and without a team logo, insinuating he is without a team and no longer in the CFL.

**Comment by gorillatrain** [comment]
Appears to now be two slots for him. One with points the other without. ![Screenshot_20210903-033257_Chrome](https://user-images.githubusercontent.com/90021072/131975975-70c3ecfe-4307-4d7e-a1c9-ab1e912bb1ac.jpg)
![Screenshot_20210903-033308_Chrome](https://user-images.githubusercontent.com/90021072/131975977-2ad68019-a9f5-48a7-b082-66bb1cc54da4.jpg)

**Comment by mdryden** [comment]
Mike Jones is one of a few players that are messed up due to bad CFL player data.

I'm hoping to have a fix soon, but in the meantime, if you want Mike Jones, you want the guy without the team.  The one on the WPG roster is the broken version.

**Comment by gorillatrain** [comment]
Right on! Thanks for the update.
