### ISSUE TITLE
Whitehead's missed field goal return?

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#64]
Not sure if it got scored properly; I don't see it in my stats or his score for our league.

I'll review this tomorrow and make sure it's corrected if it wasn't scored properly.

**Comment by SteveTaskersSon** [comment]
So missed field goals returned for a TD should count? (as long as its set in the scoring options)

**Comment by mdryden** [comment]
Yes, missed field goal returns (should) count according to however your league scores kick return yards and touchdowns.

**Comment by mdryden** [comment]
Confirmed, there was a bug in field goal returns - they straight up weren't being counted, both yards and touchdowns.

A fix for Whitehead and any other returns from this weekend is going out shortly.

This did not affect other types of returns (punt, kickoff).

This fix will only be applied for this week and future weeks.
