### ISSUE TITLE
Player Stats missing

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#65]
Sometimes some random players stats are missing. I’m not sure what causes random players to be effected but for example Ed Gainey just has no stats at all. This algae the effect of making his fantasy rank quite low and his average points per game be 0. It creates a misleading player list when your shopping for free agents.

**Comment by kamikazecanuck** [comment]
Similar issue with Ricky Collins jr.  For some reason it just counts 2 of his weeks this year.

**Comment by bohsask** [comment]
Any updates on this one?  It seems to maybe be related to guys that go on and off the IR, For example, Malik Henry and Masoli, just coming off the IR and have no history. Ahmad Thomsas and Keishawn Bierreia are missing games from before They went on the IR stint.  I'm sure there's other examples, but I'm sure it's related to the IR.

**Comment by kamikazecanuck** [comment]
Yes, Kiante Hardin on IR right now.  No stats anymore.

**Comment by kamikazecanuck** [comment]
Ricky Collins Jr. remains a good example in my league.  He's played 10 weeks but the site has chosen 4 random weeks to use for his total points and average,

**Comment by mdryden** [comment]
@bohsask I think the issue is the IR as well, but no, no updates yet.  I haven't had time to really dig into it.
