### ISSUE TITLE
Question: How are you handling when a team plays twice in a week?

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#69]
Question: How are you handling when a team plays twice in a week?

Fantesh would only take the first game?

My boyz are asking....  Thanks, David

**Comment by DamonB88** [comment]
I'm also curious. I assume (and it looks like) only the first game played will count for points, second game no points are awarded?

**Comment by mdryden** [comment]
That's correct, no points for Ottawa or Toronto players tomorrow.
