### ISSUE TITLE
Game schedual and   double playing teams for points

### ISSUE THREAD

**Issue by redblacks** [110yards/fantasy#70]
Hey
 just wondering the schedule is not looking correct currently and also wondering if its just the teams 1st game that counts for point ...... loving the new site layout its amazing  great job !

**Comment by kamikazecanuck** [comment]
I believe only the first game will count.  However, I noticed it still says right now that my Toronto guys are still going to play.  Not a big deal but hopefully not a sign of something crazy about to happen?

**Comment by mdryden** [comment]
The Monday games for Ottawa and Toronto won't count.  You'll still see score updates for the game next to the players, but the player stats will not be calculated.

**Comment by bohsask** [comment]
It's too bad the Toronto guys coudn't get credit for the point this week, as they're on bye again.  We have another 3-game week this week, what a mess.

**Comment by kamikazecanuck** [comment]
Yes I was actually going to suggest we do something crazy like that but then the week rollover and waiver wire bidding time would have only been a few hours.
