### ISSUE TITLE
Problem with scores displaying

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#71]
Lives Scores do not display on browsers on phones or if the browser is shrunk.

![Browser Problem](https://user-images.githubusercontent.com/64800266/136834892-0f48e5e1-e461-4eb6-9886-68a06beb551f.jpg)

**Comment by mdryden** [comment]
I think this is just an issue related to the flood of traffic the back end gets when games update; sometimes the scoring service doesn't respond quickly enough and you see zeros.  I'll keep an eye on it, but I don't think it's an actual issue.
