### ISSUE TITLE
Vernon Adams Jr injured

### ISSUE THREAD

**Issue by DamonB88** [110yards/fantasy#72]
I was wondering when Vernon Adams Jr status would be updated. The team has put him on the 6 game IR but i can't bid on a new QB until the status gets updated. Here's a URL for the news:
https://www.cfl.ca/2021/10/12/als-move-vernon-adams-jr-six-game-injured-list/

I believe the website updates every 3 hours but the news has been out for a day and waivers end today.

Thanks,

Damon

**Comment by bohsask** [comment]
You can actually add anyone to the IR, they don't have to be marked as injured, try it.

**Comment by mdryden** [comment]
It can take some time for players to actually appear as injured in the CFL data.  I'm not sure if the delay is teams sending the data in, or the league processing it, but there's not much I can do on my side.  As bohsask said, the IR isn't locked for reasons like this.
