### ISSUE TITLE
First week of Playoffs looks suspect

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#73]
Hey Mr. Dryden,

The first week of the playoffs for my league is blank teamwise right now but is showing 5 matchups.  Is that something I should worry about?

It's a 8 team league so should be 3 games: 3 vs 6, 4 vs 5, 7 vs 8.

Will it just correct itself in the last regular season week?
4XVWS3uyiwxXU4BAg0S7

**Comment by EElks** [comment]
It's a few days later but we are now entering our playoffs this weekend.  The schedule is filled with TBAs.  Will this be populated soon?  Thanks Michael.

**Comment by redblacks** [comment]
Hey .... our league is also showing TBD starting this week playoffs ...   4 person league 1 vs 4 2 vs 3    thanks

**Comment by mdryden** [comment]
Hey guys - sorry about this, I've been AWOL for a bit.

I'm working on a fix for the playoff calculation, it will be in place before any potential matchups start this week.

If anyone's league has already started playoffs and the first week didn't work, please let me know.

**Comment by EElks** [comment]
Thanks Michael.   That's really helpful.  The boys are looking forward to
the playoffs.
Matt

**Comment by mdryden** [comment]
@kamikazecanuck - you should see a much clearer preview of your playoffs now if you refresh.

**Comment by mdryden** [comment]
@EElks @redblacks - your playoffs have been generated now.

I'll review all of the leagues next week for any that are supposed to start, just in case it doesn't run automatically.

**Comment by kamikazecanuck** [comment]
Much better! Toilet Bowl clearly labeled as Loser Game now! Lol

**Comment by mdryden** [comment]
Next year maybe I'll make the name customizable.

**Comment by EElks** [comment]
Awesome.  Thanks Michael
