### ISSUE TITLE
2nd round playoff matchups incorrect

### ISSUE THREAD

**Issue by mdryden** [110yards/fantasy#74]
It appears that in some leagues, playoff winners weren't properly carried over to this week.

I will investigate and ensure the matchups are corrected before any games start this week.

Apologies guys, it's tough to test certain parts of the system until they actually happen.

**Comment by mdryden** [comment]
The bug here was that the calculator was using total points for instead of current week's points for to figure out the winner - just a mistake on my part.  2/3 leagues which started last week actually ended up being accidentally correct, since the favorites won.  Only the 1 league was incorrect (which I was probably lucky to spot first), because there was an upset.

I have re-run the playoffs calculation and all leagues are correct now.

**Comment by EElks** [comment]
Thanks Michael.  We were hoping to have a third place game between the losers of the semi final games.  Is this possible to set up? Thanks.

**Comment by mdryden** [comment]
Sorry, but it's not possible in the site currently.  I'll take that under consideration for next year though; a loser bracket basically, I guess?

In the meantime, teams will still accumulate points even if they don't have a matchup.  You could figure out a winner manually if you wanted.

**Comment by EElks** [comment]
Thanks Michael.  We like to have a third place game, something to consider
for next year.

I think we'll do it manually for the upcoming weekend.

Thanks for the great season.  We're happy with the site overall and look
forward to joining next year.

Matt
