### ISSUE TITLE
Problem with playoff scheduling

### ISSUE THREAD

**Issue by bohsask** [110yards/fantasy#75]
We're heading into the second round of playoffs, and the software automatically pulled the top 4 teams by record this week instead of the round 1 winners.  I can't see a way to adjust playoff matchups as commissioner, can you take a look at this?  Thanks.  

League ID: xDTpKTT4DRK3MAf4PLSD

**Comment by mdryden** [comment]
Sorry guys, looks like something went wrong during the final week calculations.

I'll work on a fix right now, should be fairly easily fixed.

**Comment by mdryden** [comment]
@davidkinetisense

**Comment by mdryden** [comment]
This should be resolved now, I've reviewed all leagues and I think everyone is good now.  I'll monitor again to ensure things work ok next week.

**Comment by davidkinetisense** [comment]
Thank you very much.  Playoffs players get excited. :)
