### ISSUE TITLE
Problem with scoring yesterday and a our playoff results.

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#76]
![image](https://user-images.githubusercontent.com/64800266/139716248-11423f43-bd16-46da-94a0-b4bc99adde7b.png)

and

![image](https://user-images.githubusercontent.com/64800266/139716332-ffa9d820-8e9c-4494-a21e-0bab54021b83.png)

We think Back to Back Champion should have won.  Can you please confirm the results for this palyoff game?

**Comment by davidkinetisense** [comment]
There are no points shown in the previous week's schedule.

![image](https://user-images.githubusercontent.com/64800266/139719370-70be22b1-28d8-4ebc-bfa8-b557c181e1dc.png)

**Comment by mdryden** [comment]
Looks like the same issue as https://github.com/mdryden/110yards/issues/75

I'm looking into this one right away.
