### ISSUE TITLE
Surprise Free Agents AKA First Come First Serve

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#78]
We're getting to that time of year where players start to sign with the CFL just now.  Sometimes they're big time Free Agent signings from a Fantasy perspective.  How does the system update these into the player list?  From a user perspective it seems like Nate Holley and Reggie Begelton just randomly appeared one day and a GM who just happened to be looking for them got them for free.

Can anything be done about that?  For example only have new players appear when waivers are still on?

**Comment by kamikazecanuck** [comment]
Well this came back to bite me.  Please add Nick Vogel right now!!!

**Comment by mdryden** [comment]
The system updates rosters every 6 hours; as soon as a player shows up on the team roster page, they should show up on the site (within 6 hrs).

At the absolute latest, they will show up when they are added to the game roster, which is usually the morning of the game. (These are updated every 15 mins).

There are no controls on these players currently, they will be free agents unless waivers are active.

I'd be open to adding something next year but honestly I'm not sure what it should be.  Lock them for 2 days?  What if they get added on game day; we wouldn't want then locked and unable to be claimed on the first week.

After the season is done I'm planning to post up a plan for next season; those who are interested and willing to participate will get an opportunity to provide feedback then and help shape the direction going forward.

**Comment by kamikazecanuck** [comment]
Ok that’s sounds interesting. Yes this is a tough one. Not sure what the solution is. I’ll try to think on it too.

**Comment by kamikazecanuck** [comment]
The only thing I can think of is, assuming next year is way less crazy with scheduling by the CFL, have waivers always resolved at noon on Wednesday.  Back in the Fantaseh days it was always Wednesday to the point we called it "Waiver Wire Wednesdays".  

A slightly extended waiver period is the only thing I can think of because if Nick Vogel was locked for 2 days or delayed this week I would have been quite screwed for my playoff matchup.  (He probably end up getting -2 points for me anyway so we'll see....)

**Comment by mdryden** [comment]
I've moved this to a discussion thread: https://github.com/mdryden/110yards/discussions/86

I'll close this ticket; if we can come up with an idea that makes sense, I'll open a new ticket.
