### ISSUE TITLE
What is the rule on when roster lock?

### ISSUE THREAD

**Issue by davidkinetisense** [110yards/fantasy#79]
What is the rule on when roster lock?  Today the roster locked at 4:55.  What is the rule?  Do you get the update from the CFL or is timed?  We had a person who waited till the last minute and missed out.  I want the rule to explain it.  Things get testing the playoffs. :)

**Comment by mdryden** [comment]
Game data is updated every 5 minutes.  The game data has a game status in it; when the status switches from PreGame to InProgress, the site considers all players on those teams to be locked.

I'm not sure when the CFL changes the status.  It could be a few minutes before the actual kickoff, so it's certainly risky to wait until the last minute.

**Comment by davidkinetisense** [comment]
Thank you for the update
