### ISSUE TITLE
Sign In 

### ISSUE THREAD

**Issue by yukonriderfan** [110yards/fantasy#8]
I sent in the request to recreate my sign in. Unfortunately, the reply went to junk mail. I tried again. I get the message that my account can't be found when I try to log in but that there's already an account when I try to re-register.

User: Yukon Rider Fan email: jsnider24@hotmail.ca

P.S. If this could take time away from development of the app then I can wait.

**Comment by yukonriderfan** [comment]
I was able to log in through Google.  I'd prefer my default email address, but again, don't want to hold up production.

**Comment by mdryden** [comment]
hey @yukonriderfan - I have found the source of this bug, I'm working on a fix now.

It seems that if you register, then don't click that first email link, you end up with a broken account, where you can't send another sign in link, but you also can't re-register.

I see that there are several accounts in the database with this issue - kamikaze and david have both been impacted as well.

Please stand by, this will be the next thing I release.

**Comment by mdryden** [comment]
The fix for this has been released, anyone affected, please try again.

**Comment by yukonriderfan** [comment]
I was able to get into the site.  However, I seem to have a new problem.  In Google I get into the site and it stops shortly at the 110 Yards 12 > 11 screen then goes to my Rouge or Bust league.  When I go in by email, it stops here.  I don't think we've ever had a league ID/password.

**Comment by mdryden** [comment]
Is your google account the same email as the other one?  If not, then you have 2 different accounts, which is why you see a different set of leagues.

**Comment by yukonriderfan** [comment]
No, I use my hotmail account as my default so that I won't miss messages (plus fewer PW's to remember).  I'd prefer to do everything through that & not Google but since I'm already in I guess I can settle for just using Google..

**Comment by mdryden** [comment]
Gotcha.  Sorry for the trouble, if not for a bug you wouldn't be stuck with the wrong email :(

On the bright side, no password to remember :)
